# main.py
# FastAPI server — exposes REST endpoints that Node.js proxies to.
# Node.js already verified the JWT before requests reach here.
#
# Run: uvicorn main:app --reload --port 8000
# Docs: http://localhost:8000/docs  (auto-generated by FastAPI)

from fastapi import FastAPI, HTTPException, Header, Query
from fastapi.middleware.cors import CORSMiddleware
from kite_service import get_oi_data, get_expiries

app = FastAPI(title="OI Analytics — Kite Service")

# Allow requests from Node.js only
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:4000",
        "https://oi-node.onrender.com",   # ← your Node.js Render URL
    ],
    allow_methods=["GET"],
    allow_headers=["*"],
)


# ── Guard: only accept requests forwarded by Node.js ─────────────
# Node.js adds X-User-Email header in server.ts when proxying.
# If that header is missing, the request bypassed our auth server.
def require_gateway(x_user_email: str = Header(default=None)) -> str:
    if not x_user_email:
        raise HTTPException(status_code=401, detail="Use auth gateway")
    return x_user_email


# ── GET /health ───────────────────────────────────────────────────
@app.get("/health")
def health():
    return {"status": "ok", "service": "oi-python"}


# ── GET /api/oi ───────────────────────────────────────────────────
# Returns the full option chain for a symbol + expiry.
# React calls: GET /api/oi?symbol=NIFTY&expiry=2025-03-27
#              via Node.js which proxies it here

@app.get("/oi")
def option_chain(
    symbol: str = Query(...),   # "..." means required
    expiry: str = Query(...),
    x_user_email: str = Header(default=None),
):
    require_gateway(x_user_email)

    allowed = ["NIFTY", "BANKNIFTY", "SENSEX"]
    if symbol.upper() not in allowed:
        raise HTTPException(status_code=400, detail=f"symbol must be one of {allowed}")

    try:
        data = get_oi_data(symbol.upper(), expiry)
        return { "symbol": symbol, "expiry": expiry, "data": data, "count": len(data) }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ── GET /api/expiries ─────────────────────────────────────────────
# Returns list of upcoming expiry dates for the dropdown.
# React calls: GET /api/expiries?symbol=NIFTY

@app.get("/expiries")
def expiries(
    symbol: str = Query(...),
    x_user_email: str = Header(default=None),
):
    require_gateway(x_user_email)
    try:
        return get_expiries(symbol.upper())
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
